### PR TITLE
Adjust icons

### PR DESCRIPTION
**Pull request by steffenkleinle**
See https://github.com/digitalfabrik/ehrenamtskarte/pull/486

### CODE REVIEW

**Comment by steffenkleinle** [comment]
Do I have to do anything else?

**Review by maxammann — CHANGES_REQUESTED** [review]
You have to follow the following steps:

**Modify Icons**

1. Take the `iconset.json` and import it to the [Maki Editor](https://www.mapbox.com/maki-icons/editor/).
2. Apply your changes and download the icons in SVG format and the iconset in JSON format.
3. Format the JSON with `cat iconset.json | jq -MS '.'` for better legibility.
4. Replace the current iconset.json in this repository with the updated one.
5. Replace all the icons in the `svgs_iconset` with the SVGs downloaded from the Make Editor.

We can do it together if you want

**Comment by steffenkleinle** [comment]
> You have to follow the following steps:
> 
> **Modify Icons**
> 
>     1. Take the `iconset.json` and import it to the [Maki Editor](https://www.mapbox.com/maki-icons/editor/).
> 
>     2. Apply your changes and download the icons in SVG format and the iconset in JSON format.
> 
>     3. Format the JSON with `cat iconset.json | jq -MS '.'` for better legibility.
> 
>     4. Replace the current iconset.json in this repository with the updated one.
> 
>     5. Replace all the icons in the `svgs_iconset` with the SVGs downloaded from the Make Editor.
> 
> 
> We can do it together if you want

I did just replace the current paths in the iconset.json with the paths of the new icons. I uploaded the iconset.json to maki and everything looks fine afaict. Could you have a look as well please?

**Comment by maxammann** [comment]
I imported the JSON into the editor and exported the icons.

**Pull request merged**
